# Use the official Nginx image
FROM nginx:alpine

# Copy the Nginx configuration file
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Set the working directory to /var/www/html
WORKDIR /var/www/html
